apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b-dep
  template:
    metadata:
      labels:
        app: b-dep
    spec:
      containers:
      - name: server
        image: nygma13/nginx-exerc3:latest
        env:
        - name: URL
          value: "https://www.csd.uoc.gr"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: b-svc
spec:
  type: LoadBalancer
  selector:
    app: b-dep
  ports:
  - port: 8080
    targetPort: 80